### ISSUE TITLE
[Feature Request] Support `limit` key for pool elements

### ISSUE THREAD

**Issue by SettingDust** [Apollounknowndev/lithostitched#1]
`limit` can make the elements spawn limited times instead of only weighted

I'm willing to contribute but not sure if it is out of the scope of this mod

A standalone mod that can limit any element in any pool that is data-driven may be better.

**Comment by Apollounknowndev** [comment]
Guaranteed elements in jigsaw structures is a part of Lithostitched 1.1, information on how it works is on the wiki [here](https://github.com/Apollounknowndev/lithostitched/wiki/Structure-Utilities#structure-types).

**Comment by SettingDust** [comment]
A bit confused. How can I make it work with the `worldgen_modifier` injected element?

**Comment by Apollounknowndev** [comment]
It's not a part of template pools, it's baked into the `lithostitched:jigsaw` structure type. It's not quite the same thing, but it was by far the easiest way to implement it.

**Comment by SettingDust** [comment]
Alr. I have two points.
1. How about something like pool injection to inject elements into guaranteed elements? 
2. How can I do something like only spawn 1 specific structure for the target pool? I'm not quite sure how min depth works

**Comment by Apollounknowndev** [comment]
1. Interesting idea, might end up allowing guaranteed elements to run modifier predicate checks in the future.
2. `min_depth` controls how many jigsaw connections away the element must be from the starting element at a minimum. For example, a `min_depth` of 5 means that there must be at least 5 jigsaw pieces between the start piece and the guaranteed piece.

**Comment by Apollounknowndev** [comment]
Ohh, do you mean to have something that says "generate this piece **up to** x number of times"?

**Comment by SettingDust** [comment]
> Ohh, do you mean to have something that says "generate this piece **up to** x number of times"?

ya XD
Just like https://modrinth.com/mod/structure-pool-api

If you are going to include it as a feature I will contribute. Or I will create a standalone mod for that

**Comment by SettingDust** [comment]
Since you assigned yourself. Should I contribute or wait for you?

**Comment by Apollounknowndev** [comment]
I've gotten it mostly implemented, just need to fix a few... *minor* issues. It'll be in Lithostitched 1.1.3.

![2024-01-17_23 00 01](https://github.com/Apollounknowndev/lithostitched/assets/102649729/d183da6a-ee8b-4289-9357-cc8946011b13)

**Comment by Apollounknowndev** [comment]
Added in Lithostitched v1.1.3, details on the pool element type are here:
https://github.com/Apollounknowndev/lithostitched/wiki/Structure-Utilities#limited

**Comment by SettingDust** [comment]
Awesome!
