### ISSUE TITLE
[FR] Add function to create GuaranteedPoolElement for data generation

### ISSUE THREAD

**Issue by SettingDust** [Apollounknowndev/lithostitched#10]
For now the constructors are protected that can't be created in data generator

**Comment by SettingDust** [comment]
The `GuaranteedPoolElement#GUARANTEED_TYPE` isn't the type instance in registries. 
We can't construct the instance and pass as any param.
`GuaranteedPoolElement#GUARANTEED_TYPE` should be fetched from registry. Or should be passed to registry instead of construct the new one.
A catalog class like `StructurePoolElementType` in vanilla is fine

**Comment by Apollounknowndev** [comment]
Done in v1.2.2
