### ISSUE TITLE
World on servers arent generating like they should

### ISSUE THREAD

**Issue by pewblaze** [Apollounknowndev/lithostitched#11]
Hi i updated the mod today & after creating a new world on a server the biomes/generation isnt like it should be.
singleplayer world generated fine & as intended.
I think (not sure) that it cant recognize datapacks like it should? 

I have William Wythers' Overhauled Overworld as a datapack & no matter what i did it couldnt generate the biomes like they should be in the datapack. it could be a mod incom. but i just wanted to share it :) 

i downgraded lithostitched and everything works fine :)

**Comment by Apollounknowndev** [comment]
What?

**Comment by pewblaze** [comment]
Sorry missclicked the enter key D:

**Comment by Apollounknowndev** [comment]
I'm still confused what you're talking about. What exactly isn't working?

**Comment by pewblaze** [comment]
Sorry about that. I tried to get the error again & now its gone. So nevermind ^^"
