### ISSUE TITLE
[1.21 Fabric] BCLib Incompatibility 

### ISSUE THREAD

**Issue by chorbintime** [Apollounknowndev/lithostitched#12]
Creating a world with both Lithostitched and BCLib installed gives the following crash:
https://mclo.gs/zFsjw70
https://mclo.gs/ixFmeGs

Adding a mod that depends on Lithostitched, in this case Stony Cliffs Are Cool, seems to give a different crash report:
[crash-2024-07-12_09.50.19-client.txt](https://github.com/user-attachments/files/16195761/crash-2024-07-12_09.50.19-client.txt)

Removing Lithostitched and its dependents fixes the issue.

**Comment by Apollounknowndev** [comment]
This appears to be an issue with WorldWeaver, I have [forwarded the issue to them](https://github.com/quiqueck/WorldWeaver/issues/8).

**Comment by chorbintime** [comment]
Fixed in the latest WorldWeaver release. Thank you!
