### ISSUE TITLE
Crash on Fabric 1.20.1

### ISSUE THREAD

**Issue by NolanHewitt** [Apollounknowndev/lithostitched#13]
[crash-2024-09-21_21.11.47-server.txt](https://github.com/user-attachments/files/17087987/crash-2024-09-21_21.11.47-server.txt)

Got a crash where the error log seems to mainly mention lithostitched.

This happened on a superflat world, the only structures mod I have that I'm aware of using lithostitched is CTOV's villages.

**Comment by Apollounknowndev** [comment]
It's definitely a Lithostitched issue, although it seems to be a conflict with another mod given just Lithostitched + CTOV working fine. Not sure what mod it would be, further investigation will be needed.

![2024-09-21_23 09 49](https://github.com/user-attachments/assets/91309739-f7f8-425d-a0ff-82b9ebf86f3f)

**Comment by NolanHewitt** [comment]
Unfortunately it’ll be hard for me to test as it seems to be a rare crash. Rare enough its only happened to me once so far. Might be a one off issue that doesn’t happen again but I wanted to make the issue and post my crash report here just in case.

**Comment by Apollounknowndev** [comment]
Fixed in 1.3.8.
