### ISSUE TITLE
Minimal side effect in mixin

### ISSUE THREAD

**Issue by SettingDust** [Apollounknowndev/lithostitched#16]
The `ChunkMapMixin` is redirecting `RandomState#create`. 
Why not inject at return and use a `RandomStateAccessor` set the values instead of replacing the object?

Can you push the latest code so that I can contribute?

**Comment by Apollounknowndev** [comment]
I don't see why this would matter? It gets applied the same either way, and `WrapOperation` means it won't break if another mod mixins the same method.

**Comment by SettingDust** [comment]
It's redirecting on 1.20.1

**Comment by Apollounknowndev** [comment]
It's *far* more effort to move off of a `@Redirect`; The object has to basically be reconstructed. Unless you have a specific use case where this breaks another mod, it won't be fixed.

**Comment by SettingDust** [comment]
What's to reconstruct? `WrapOperation` or `Inject` is enough to modify the field like how the Lithostitched do it now

**Comment by Apollounknowndev** [comment]
You can't simply swap out the noise router in the random state, all the noise router fields need to be mapped/visited again and several fields need to be re-accessed. It's a hassle. Hard to explain without showing the code which I can't access at the moment.
