### ISSUE TITLE
Failure to load after update to 1.3.5 for Forge 1.20.1

### ISSUE THREAD

**Issue by thomwoosley** [Apollounknowndev/lithostitched#18]
When attempting to load a world, I got a message about corrupted datapacks.  This happened for every world I had.  It offered a safe mode, but that wouldn't load either.

After downgrading to 1.3.4, I was able to load all of the worlds again.

**Comment by Apollounknowndev** [comment]
Issue has been found and fixed, will be released alongside some minor technical changes soon.

**Comment by NolanHewitt** [comment]
Have a similar issue on fabric. Not sure if its the same issue effecting the fabric 1.20.1 version of 1.3.5

**Comment by Apollounknowndev** [comment]
Fabric was affected by the same issue, both platforms have been fixed in the 1.3.7 release.

**Comment by rojowalker** [comment]
This error is now in screen
File lithostitched-forge-1.20.1-1.3.7.jar is not a valid mod file.

**Comment by ShinyPantsReal** [comment]
> This error is now in screen File lithostitched-forge-1.20.1-1.3.7.jar is not a valid mod file.

Having the same problem here

**Comment by Apollounknowndev** [comment]
Reupload going out now. I hate forge.
