### ISSUE TITLE
Failed to inject structures into template pool.

### ISSUE THREAD

**Issue by ChoiceTheorem** [Apollounknowndev/lithostitched#2]
With the same datapack. Lithostitched for 1.20.1 Fabric failed to add pieces into template pools compared with 1.20.2 Fabric
1.20.1
![2024-01-23_21 08 07](https://github.com/Apollounknowndev/lithostitched/assets/46421477/23c4ac02-34d8-447a-a708-b8abebc29fb9)
1.20.2
![2024-01-23_21 12 24](https://github.com/Apollounknowndev/lithostitched/assets/46421477/1f88184c-83b6-45ca-8211-93a46c280fb5)

**Comment by Apollounknowndev** [comment]
Can you send the datapack so I can test it?

**Comment by ChoiceTheorem** [comment]
Here's the datapack! [data.zip](https://github.com/Apollounknowndev/lithostitched/files/14038583/data.zip)

**Comment by Apollounknowndev** [comment]
Can I get some more information on how to replicate the issue? i.e. which structure(s) have the issue, which mods needs to be installed?

**Comment by ChoiceTheorem** [comment]
1. All CTOV villages
2. CTOV interact with lithostitched to add structures from beautify,
friends and foes, croptopia, essentially every mod.

**Comment by Apollounknowndev** [comment]
Just tried Friends and Foes with Lithostitched 1.1.4a on both 1.20.1 and 1.20.2. It works fine on both versions, so I don't know what to tell you.

![image](https://github.com/Apollounknowndev/lithostitched/assets/102649729/c1ab445b-1233-42dd-bad2-2d229c2df17c)

**Comment by ChoiceTheorem** [comment]
Will try to replicate it on my side, Thanks!

**Comment by ChoiceTheorem** [comment]
Replicated, issue successfully resolved!
