### ISSUE TITLE
"lithostitched:jigsaw" won't place elements correctly

### ISSUE THREAD

**Issue by SettingDust** [Apollounknowndev/lithostitched#4]
I'm on 1.20.1 Fabric

https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/blob/1.20/common/src/main/resources/data/ctov/worldgen/structure/small/village_beach.json

I replaced the `"minecraft:jigsaw"` to `"lithostitched:jigsaw"`. 
The structures in first pic is `ctov:village/beach/jobsite/wizard_tower` which injected by Lithostitched

**lithostitched:jigsaw**
![图片](https://github.com/Apollounknowndev/lithostitched/assets/19922286/59063dcd-ac57-47cc-8a8b-49d4a3975bfa)

**minecraft:jigsaw**
![图片](https://github.com/Apollounknowndev/lithostitched/assets/19922286/f5790564-42fa-4690-8d86-8e18192cc619)

Disabled the injection and works. Have no idea of the reason.
![图片](https://github.com/Apollounknowndev/lithostitched/assets/19922286/05d68486-1c46-4c4f-9d49-b57e6095e8d7)

**Comment by SettingDust** [comment]
Interesting after using "lithostitched:guaranteed" for injection.

![图片](https://github.com/Apollounknowndev/lithostitched/assets/19922286/09d905ec-e860-43d5-9bad-5871461739be)

**Comment by SettingDust** [comment]
With debugging. The `lithostitched$structurePoolElements` won't include the templates. There are only the injected pieces.
I found the reason here set it https://github.com/Apollounknowndev/lithostitched/blob/1.20.1/common/src/main/java/dev/worldgen/lithostitched/worldgen/modifier/AddTemplatePoolElementsModifier.java#L90 
Is it intended? I think the original one should be iterated here instead of the `elements()`
![图片](https://github.com/Apollounknowndev/lithostitched/assets/19922286/e6d45e54-77d5-4fb7-b446-6199c4f990ac)

**Comment by SettingDust** [comment]
It's fine :D
![图片](https://github.com/Apollounknowndev/lithostitched/assets/19922286/e4a56a78-c7b4-4d24-9b60-600779c664b1)

**Comment by Apollounknowndev** [comment]
Fixed in 1.1.5.
