### ISSUE TITLE
The alternative jigsaw is smaller than jigsaw from vanilla

### ISSUE THREAD

**Issue by SettingDust** [Apollounknowndev/lithostitched#6]
The 3 bottom is `lithostitched:jigsaw` and the 2 top is `minecraft:jigsaw`

The structure is 
https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/blob/1.20/common/src/main/resources/data/ctov/worldgen/structure/large/village_beach.json

![图片](https://github.com/Apollounknowndev/lithostitched/assets/19922286/c0aca186-fc0a-4726-84a9-bc2a5a82fb7e)

**Comment by Apollounknowndev** [comment]
Can't replicate with vanilla structures.

Vanilla jigsaw above, Lithostitched jigsaw below
![image](https://github.com/Apollounknowndev/lithostitched/assets/102649729/eac02a17-f261-4bc5-a874-3cd9ac0ede1c)

The upper structures in your image actually look like they're too big, as a `size` of 5 shouldn't allow them to reach that limit. No clue what that is about though.

**Comment by SettingDust** [comment]
I tried removing the injection but got the same result. Is there some hint for this? @ChoiceTheorem
![图片](https://github.com/Apollounknowndev/lithostitched/assets/19922286/6d3faf3a-7ef7-443c-8843-d0513beeb569)

EDIT: Same with 1.1.5. NTW, the injection is fixed.
![图片](https://github.com/Apollounknowndev/lithostitched/assets/19922286/3f73fb0b-c944-4150-998b-df08cdf85177)

**Comment by SettingDust** [comment]
Failing to figure out the reason. I think I changed nothing.

The instance exported with Prism Launcher
[CTOV Datapacks.zip](https://github.com/Apollounknowndev/lithostitched/files/14228407/CTOV.Datapacks.zip)

**Comment by ChoiceTheorem** [comment]
Hmmm, indeed they are identical. The different are structure type. Have no idea why it doesn't work with CTOV though.

**Comment by Apollounknowndev** [comment]
Unintentionally found and fixed the bug while working on the 1.20.5 update, will be backporting and releasing the fix in 1.1.6.

**Comment by SettingDust** [comment]
> Unintentionally found and fixed the bug while working on the 1.20.5 update, will be backporting and releasing the fix in 1.1.6.

wow. I'm looking forward to the fix push to Github, I want to see the reason

**Comment by Apollounknowndev** [comment]
The difference is changing a single word, it's so unbelievably stupid

**Comment by Apollounknowndev** [comment]
Completely forgot about this until just now :P
1.1.6 rolling out now.

**Comment by SettingDust** [comment]
> Completely forgot about this until just now :P 1.1.6 rolling out now.

@Apollounknowndev The code on Github won't update?

**Comment by Apollounknowndev** [comment]
Pushed

**Comment by SettingDust** [comment]
So, `return` to `continue` XD. lul
