### ISSUE TITLE
Unable to remove features of other mods?

### ISSUE THREAD

**Issue by Agonizes** [Apollounknowndev/lithostitched#8]
Hi Apollo,

I'm fairly certain this is not a bug and just me being stupid, but I can't for the life of me figure out how to remove biome features of other mods and I hope you can help me:
 
```
{
 "type": "lithostitched:remove_features",
  "predicate": {
    "type": "lithostitched:true"
  },
  "biomes": "#minecraft:is_overworld",
  "features": "bloomingnature:jungle_ebony_tree",
  "step": "vegetal_decoration"
}
```

The error that is thrown is:

>  java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/placed_feature]: [bloomingnature:jungle_ebony_tree]

It's looking for the data in the minecraft root data instead of the data of the bloomingnature mod and I have no idea how to make it direct correctly to the data of bloomingnature.
Thanks in advance,

**Comment by Apollounknowndev** [comment]
I just took a look at Blooming Nature's worldgen files, there is no `jungle_ebony_tree` placed feature.
![image](https://github.com/Apollounknowndev/lithostitched/assets/102649729/18fee2c5-ae7b-4687-83d5-34e0726e25b1)

**Comment by Apollounknowndev** [comment]
I'd recommend overriding [bloomingnature:jungle_trees](https://github.com/satisfyu/BloomingNature/blob/1.20.1/common/src/main/resources/data/bloomingnature/worldgen/configured_feature/jungle_trees.json) and removing the `jungle_ebony_tree_checked` feature from the `features` list to remove the ebony trees.
