### ISSUE TITLE
[HELP NEEDED]

### ISSUE THREAD

**Issue by MMG778** [Apollounknowndev/lithostitched#9]
Hello Apollo!

I would like to remove cypress trees from regions unexplored old growth bayou biome and replace them with Wilder Wild's cypress trees because I like the old growth bayou biome but not the trees and I need an example on how to do it correctly. Also I have no clue how and where to put the worldgen modifier configuration file that we need to create.

Regions Unexplored biome list with tags: https://gist.github.com/catter1/1f90b77263e3746c20c1fd93a7393f69#old-growth-bayou

Regions Unexplored cypress tree: regions_unexplored:cypress_logs, regions_unexplored:cypress_leaves

Wilder Wild github: https://github.com/FrozenBlock/WilderWild/tree/1.20.1

Wilder Wild cypress tree: wilderwild:cypress_logs, wilderwild:cypress_leaves

Thank you in advance!

**Comment by SettingDust** [comment]
https://github.com/Apollounknowndev/lithostitched/wiki/Worldgen-Modifiers#redirect_feature

https://github.com/FrozenBlock/WilderWild/blob/1.20.1/src/main/generated/data/wilderwild/worldgen/configured_feature/cypress.json

Find the tree feature yourself for Regions Unexplored. 

There are variants in WilderWild. You can find them in the dir
